car_brands = [
    "Porsche",
    "Ferrari",
    "Maserati",
    "Pagani",
    "Alfa Romeo",
    "Chrysler",
    "Nissan",
    "Bugatti",
    "Rimac",
    "Renault",
    "Toyota",
    "Volkswagen",
    "Peugeot",
    "Polestar",
    "McLaren",
    "Bentley",
    "Lamborghini",
    "Aston Martin",
    "Gumpert",
    "Caterham",
    "Land Rover",
]