bands = [
"Metallica",
"Led Zeppelin",
"Foo Fighters",
"Dragonforce",
"Frank Zappa",
"Rage Against the Machine",
"Black Sabbath",
"Deep Purple",
"The Clash",
"Limp Bizkit",
"Drowning Pool",
"Linkin Park",
"Disturbed",
"System of a Down",
"The Rolling Stones",
"Aerosmith",
"Fleetwood Mac",
"Red Hot Chili Peppers",
"Bon Jovi",
"The Animals",
"Lynyrd Skynyrd",
"David Bowie",
"Pink Floyd",
"Soundgarden"
]